baseURL: https://www.bueti-online.ch
languageCode: en-us
title: Personal website and blog
theme: PaperMod

# theme: ../..

#########################################
######## Uncomment this option ##########
#########################################
# This options specify where to look for the images used in this config
# The default value is the "asset" directory of this theme
assetDir: "static"

# Option to specify the default language of the theme
# I.e., the landing language of your root
DefaultContentLanguage: en

# Option to disable additional language in your site.
# disableLanguages: ["ru"]

# Option to specify that all links will be open in a new tab.
blackfriday:
  hrefTargetBlank: true

Taxonomies:
  tag: "tags"

# Supported fonts are:
# https://fonts.google.com/

# Icons taken from:
# https://konpa.github.io/devicon/
# https://bulkitv2.cssninja.io/_components-icons-fa.html

params:
  # Site settings
  env: production
  description: "Personal website and blog by Benjamin Buetikofer"
  keywords: [Benjamin, Buetikofer, blog, personal, SRE, DevOps]
  author: Benjamin Buetikofer
  images: ["/images/me.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  # Analytics
  plausible:
    enable: true
    domain: bueti-online.ch

  # Home page
  homeInfoParams:
    Title: "Hi there 👋"
    Content: Welcome to my personal website and blog. I'm passionate about
      building resilient systems and effective teams. When I'm not optimizing infrastructure or diving into DevOps practices, you'll find me in the mountains.

  # Social icons
  socialIcons:
    - name: bluesky
      url: "https://bsky.app/profile/bueti-online.ch"
    - name: mastodon
      url: "https://hachyderm.io/@bbu"
    - name: github
      url: "https://github.com/bueti"
    - name: linkedin
      url: "https://linkedin.com/in/benjamin-bütikofer-59584b64"

  # Menu
  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["bluesky", "ycombinator", "linkedin", "reddit"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  # Search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ["title", "permalink", "content"]

  # Assets
  assets:
    disableHLJS: true
    disableFingerprinting: true
    favicon: "/images/favicon.svg"
    favicon16x16: "/images/favicon.svg"
    favicon32x32: "/images/favicon.svg"
    apple_touch_icon: "/images/favicon.svg"
    safari_pinned_tab: "/images/favicon.svg"

  # Label
  label:
    text: "Benjamin Buetikofer"
    icon: "/images/me.png"
    iconHeight: 35

  # Profile mode
  profileMode:
    enabled: false
    title: Benjamin Buetikofer
    subtitle: "Personal website and blog"
    imageUrl: "/images/me.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Benjamin Buetikofer

  # Comments - Giscus (GitHub Discussions)
  giscus:
    repo: "bueti/webpage"
    repoId: "MDEwOlJlcG9zaXRvcnkyOTgwMzk4NjI="
    category: "Announcements"
    categoryId: "DIC_kwDOEcO6Ns4CsJDs"
    mapping: "pathname"
    strict: "0"
    reactionsEnabled: "1"
    emitMetadata: "0"
    inputPosition: "top"
    theme: "preferred_color_scheme"
    lang: "en"
    loading: "lazy"

# Menu
menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 10
    - identifier: books
      name: Books
      url: /books/
      weight: 20
    - identifier: talks
      name: Talks
      url: /talks/
      weight: 30
    - identifier: about
      name: About
      url: /about/
      weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 50

# Site-wide content sorting
pagination:
  pagerSize: 10
  path: "page"

# Taxonomies sorting
taxonomies:
  tag: "tags"
  category: "categories"

# Output formats for search
outputs:
  home:
    - HTML
    - RSS
    - JSON

privacy:
  youtube:
    privacyEnhanced: true

###################################################################
################## multilanguage support options ##################
###################################################################
languages:
  en:
    languageName: English
    weight: 1
